### ISSUE TITLE
Upgrade to font awesome v4.4 or newer

### ISSUE THREAD

**Issue by felixhayashi** [TheDiveO/TW5FontAwesome#2]
Hi @TheDiveO 

would it be possible, to upgrade your plugin to Font Awesome v4.4?

Many thanks
-Felix

**Comment by Spangenhelm** [comment]
@felixhayashi Hey there ;-)

Apparently @TheDiveO has not been active for a very long time (like a year or so... don't know what happened, nothing bad i hope) so i'm affraid no-one will answer you and i'm not sure if it is worth leaving this open, in case you could re-open it later. Mine was opened at the beginning of 2015 and i never got any news since then.

-S

**Comment by felixhayashi** [comment]
> so i'm affraid no-one will answer you and i'm not sure if it is worth leaving this open, in case you could re-open it later. Mine was opened at the beginning of 2015 and i never got any news since then.

Salut @Spangenhelm. I changed the title to make this issue valid in the future too ;) Tobias also provides a font awesome plugin so I guess we stick with his version as it is up-to-date.

**Comment by thediveo** [comment]
Sorry for the long period of hibernation. As of these days, I've upgraded my plugin to Font Awesome 4.7.0, with additional maintenance to the plugin and CSS itself.

**Comment by felixhayashi** [comment]
cool :+1:
