### ISSUE TITLE
TiddlyMap and FontAwesome not working anymore in the current version?

### ISSUE THREAD

**Issue by IvoAlexander** [TheDiveO/TW5FontAwesome#5]
Hello there,

apologies if i am not following proper rules - this is the first time I use GitHub and my first post.
I try to use TiddlyMap and FontAwesome in the newest versions and for some reason the icons are not working in the map. Here is what I did:

1. Downloaded the current TiddlyWiki from here: [https://tiddlywiki.com/](https://tiddlywiki.com/)
2. dragged the plugin from here [http://thediveo.github.io/TW5FontAwesome/output/fontawesome.html](http://thediveo.github.io/TW5FontAwesome/output/fontawesome.html)  (as recommended) into the empty TiddlyWiki.
3. Installed the TW5-TiddlyMap as recommended here [http://tiddlymap.org/](http://tiddlymap.org/)
4. The link decoration is working fine, the Font Awesome control tab is there, all good.
5. I opened the demo map and set the FA-icon entry to f206 of the "Have fun with"-node.
6. The Icon is not rendered, instead there is a black framed square with f205 in it, not the Bicycle I would expect...

What am I doing wrong here?

Kind regards

**Comment by thediveo** [comment]
The older plugin versions of FontAwesome were based on Font Awesome 4, the newer plugin releases base on Font Awesome 5 (FA5). Unfortunately, Font Awesome 5 brought some changes, such as separating the icons into three separate icon font files. I suspect that tiddlymap needs to be adapted to the new scheme, probably by pulling in the FA5-provided backward compatibility stylesheet. I haven't added this to my plugin because it makes the new features of FA5 at least partly inaccessible. I would suggest you to contact the author of tiddlymap.

**Comment by IvoAlexander** [comment]
Thanks for that explanation, I contacted the author of tiddlymap, as recommended, will keep you in the loop
